# Generated by Django 4.0.4 on 2022-06-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank='True', null='True', upload_to=''),
            preserve_default='True',
        ),
    ]
